In [5]:
import numpy as np

a=[1, 2, 4]
b = np.array(a)
print(b)
print(type(b))

[1 2 4]
<class 'numpy.ndarray'>


In [9]:
# numpy creates array of homogeneous element
#use dtype to cast to one type
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = int)
print(b)

[1 2 3 5 4]


In [11]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [13]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [16]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
b = np.zeros(4)
b

array([0., 0., 0., 0.])

In [20]:
# creating an array and initializing it with some value
b = np.full(3, 4)
b

array([4, 4, 4])

In [25]:
b= np.empty((2, 2), dtype = int)
b

array([[     94374078114288,     140699132280048],
       [7311068618034541413, 2466321603649696626]])

In [27]:
a = np.empty(4, dtype = int)
print(a)


[7236833184642769452 7881144752318672485 7310875413622977637
 7308895138223563308]


In [30]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#control over the step value
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#constrol over the no of samples
b = np.linspace(2, 10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [40]:
#generating a square matrix
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
#genrate a mXn matrix
b =  np.eye(3, 4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
b = np.random.rand(3)
b

array([0.82041174, 0.69528268, 0.98899333])

In [46]:
b = np.random.rand(2, 3)
b

array([[0.64083026, 0.78030968, 0.05815139],
       [0.68308592, 0.30034466, 0.28291514]])

In [48]:
#smaples from range 0 to 10
b = np.random.rand(2, 3) * 10
b

array([[5.93958493, 6.74535539, 3.69641804],
       [5.13709572, 1.26794364, 4.35150065]])

In [49]:
# np.random.int()

In [51]:
a = np.array([0, 1, 2, 3])
a.shape


(4,)

In [53]:
np.random.rand()

0.2203054125759616

In [63]:
np.random.randint(4, 10, (2, 3))

array([[4, 4, 9],
       [6, 8, 7]])

In [59]:
import numpy as np
li = [1, 2, 3, 4, 5]
arr = np.array(li)
print(arr[1:4])

[2 3 4]


In [69]:
#slicing in 2d array
li = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(li)
print(arr2[1][1:3])
print(arr2[0:3, 2])
#slicing a square
print(arr2[1:3, 1:3])

[5 6]
[3 6 9]
[[5 6]
 [8 9]]


In [71]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [85]:
li = [1, 2, 3,4,5]
a = np.random.randint(1, 20, 5)
b= np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[11 18 19 11  1]
[15 15  6  9 15]


In [81]:
# inc val of list
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [86]:
# inc val of np arr
a = a+1
a

array([12, 19, 20, 12,  2])

In [87]:
c =a +b
c

array([27, 34, 26, 21, 17])

In [88]:
f = a/b
f

array([0.8       , 1.26666667, 3.33333333, 1.33333333, 0.13333333])

In [91]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())

[12 19 20 12  2]
65
13.0
2
4


In [93]:
print(a)
print(b)


[12 19 20 12  2]
[15 15  6  9 15]


In [95]:
a > b

array([False,  True,  True,  True, False])

In [97]:
a<b

array([ True, False, False, False,  True])

In [100]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [102]:
#Boolean Indexing
print(b > 10)

[ True  True False False  True]


In [107]:
bool_arr = b>10
print(b)
# print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[15 15  6  9 15]
[15 15 15]


In [111]:
print(3 and 2)

2


In [113]:
b[b<10] = 66
b

array([15, 15, 66, 66, 15])

In [1]:

a = np.where(b == 66)
print(type(a))
print(type(a[0]))
for i in a:
    print(i)

NameError: name 'np' is not defined

In [3]:
import numpy as np
a = np.random.randint(1, 30, (5, 6))
print(a)

[[19 11  9  2 15  4]
 [ 2 24 28 14  3  3]
 [ 1 13 24 15  6 19]
 [20 20 18 14 17 26]
 [20  5  7 14 17 15]]


In [7]:
bool_arr = a > 20
print(bool_arr)

[[False False False False False False]
 [False  True  True False False False]
 [False False  True False False False]
 [False False False False False  True]
 [False False False False False False]]


In [9]:
ans = a[bool_arr]
ans

array([24, 28, 24, 26])

In [12]:
b = a
b[bool_arr] = 100
b

array([[ 19,  11,   9,   2,  15,   4],
       [  2, 100, 100,  14,   3,   3],
       [  1,  13, 100,  15,   6,  19],
       [ 20,  20,  18,  14,  17, 100],
       [ 20,   5,   7,  14,  17,  15]])

In [14]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[5 9]
 [6 6]]


In [17]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [19]:
# print(c[c_bool])

In [28]:
print(b)
bool_arr = b[:, 2] == 100
# print(bool_arr)
print()
b[bool_arr, 2] = 99
print(b)

[[ 19  11   9   2  15   4]
 [  2 100 100  99   3   3]
 [  1  13 100  99   6  19]
 [ 20  20  18  14  17 100]
 [ 20   5   7  14  17  15]]

[[ 19  11   9   2  15   4]
 [  2 100  99  99   3   3]
 [  1  13  99  99   6  19]
 [ 20  20  18  14  17 100]
 [ 20   5   7  14  17  15]]


In [34]:
import numpy as np
a = np.array( [[21, 20, 19, 18, 17],
  [16, 15, 14, 13 ,12],
  [11, 10,  9,  8,  7],
  [ 6,  5,  4 , 3, 2]])

a = a[a[:,1].argsort()]
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


## Numpy Broadcasting
mathematicals operations to be performed on the matrices having different shapes

In [37]:
import numpy as np

x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

print(x)
print(y)

[[1 9 4]
 [4 4 4]
 [8 7 2]]
[[5 5 6]
 [8 8 9]
 [1 2 6]]


In [38]:
ans = x-y;
print(ans)

[[-4  4 -2]
 [-4 -4 -5]
 [ 7  5 -4]]


In [39]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, 3)
print(x)
print(y)

[[6 7 2]
 [9 5 6]
 [7 3 3]]
[3 8 1]


In [41]:
#it auto completes itself using previous elements
# if the dimension of one array is 1D
ans = x-y
print(ans)

[[ 3 -1  1]
 [ 6 -3  5]
 [ 4 -5  2]]


In [42]:
x = np.random.randint(1, 10, (3, 2))
y = np.random.randint(1, 10, (2, 3))
print(x)
print(y)

[[4 2]
 [4 1]
 [6 5]]
[[4 5 1]
 [2 5 1]]


In [44]:
y = np.transpose(y)
ans = x-y
print(ans)

[[ 0  0]
 [-1 -4]
 [ 5  4]]


In [45]:
x = np.random.randint(1, 10, (3, 1))
y = np.random.randint(1, 10, (1, 3))
print(x)
print(y)

[[3]
 [7]
 [8]]
[[1 6 4]]


In [46]:
ans = x-y
print(ans)

[[ 2 -3 -1]
 [ 6  1  3]
 [ 7  2  4]]


In [56]:
import csv
import numpy as np

file_obj = open('year2017.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])    
    wounded.append(row['Wounded'])
    country.append(row['Country'])
# print(killed)

np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed == ""] = "0.0"
np_wounded[np_wounded ==""] = "0.0"

np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

killed_wounded = np_killed+np_wounded
killed_wounded = np.array(killed_wounded, dtype = int)

np_country = np.array(country)

bool_arr = np_country == "India"
ans = killed_wounded[bool_arr]
print(np.sum(ans))

1167


In [24]:
import csv 
import numpy as np
file_obj = open("terrorismData.csv")
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
for row in data:
    killed.append(row['Day'])
# print(killed)
np_killed = np.array(killed)
np_killed = np.array(killed, dtype = float)
np_killed = np.array(killed, dtype = int)
boolArr1 = (np_killed >= 10)
boolArr2 = (np_killed <= 20)
boolArr = boolArr1 & boolArr2
ans = np_killed[boolArr]
print(ans)
print(len(ans))

[10 11 12 ... 20 20 20]
66330


In [36]:
import csv
import numpy as np

file_obj = open("terrorismData.csv")
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
for row in data:
    killed.append([row['Day'], row['Month'], row['Year']])
np_killed = np.array(killed, dtype = int)
np_killed = np_killed[np_killed[:,2] == 2010]
np_killed = np_killed[np_killed[:,1] == 1]
np_killed = np_killed[np_killed[:,0] >= 1]

print(np_killed.shape[0])


271


In [49]:
import csv
import numpy as np

killed = [1, 2, 3, 4]

npArray = np.array(killed)
print(np.argmax(npArray))

3


In [53]:
import csv
import numpy as np
killed = []
wounded = []
group = []
city = []
with open("terrorismData.csv") as file_obj:
    data = csv.DictReader(file_obj, skipinitialspace = True)
    
    for row in data:
        if(row['Year'] == '1999'):
            if(row['Month'] >= '5' and row['Month'] <= '7'):
                killed.append(row['Killed'])
                wounded.append(row['Wounded'])
                group.append(row['Group'])
                city.append(row['City'])

np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_group = np.array(group)

np_killed[np_killed == ""] = "0.0"
np_wounded[np_wounded == ""] = "0.0"

np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)
np_killed = np.array(np_killed, dtype = int)
np_wounded = np.array(np_wounded, dtype = int)

idx = np.argmax(np_wounded)
# print(idx)
# print(city[idx])
print(str(np_wounded[idx]) + " " + city[idx] + " " + group[idx])

218
Unknown


In [61]:
import csv
import numpy as np

killed = []
wounded = []
state = []

with open("terrorismData.csv") as file_obj:
    data = csv.DictReader(file_obj, skipinitialspace = True)
    
    for row in data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        state.append(row['State'])
        
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_state = np.array(state)

np_wounded = np_wounded[(np_state == "Jharkhand") | (np_state == "Odisha") | (np_state == "Andhra Pradesh") | (np_state == "Chhattisgarh")]
np_killed = np_killed[(np_state == "Jharkhand") | (np_state == "Odisha") | (np_state == "Andhra Pradesh") | (np_state == "Chhattisgarh")]

np_killed[np_killed == ""] = "0.0"
np_wounded[np_wounded == ""] = "0.0"

np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)
np_killed = np.array(np_killed, dtype = int)
np_wounded = np.array(np_wounded, dtype = int)

np_wounded = np_killed + np_wounded
print(np_wounded.sum())

5628
